name: ci/cd
on:
  push:
    paths-ignore:
      - '**.md'
      - LICENCE
    branches:
      - master
  pull_request:
env:
  DEFAULT_GO_VERSION: '1.20'
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Cache Go dependencies
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/go/pkg/mod
            /home/runner/.cache/go-build
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          check-latest: true
          cache-dependency-path: ${{ env.GOMODCACHE }}
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run linter
        run: make lint
      - name: Run test
        run: make test
